# Generated by Django 5.2.4 on 2025-08-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_creation_date_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
