# Generated by Django 5.2.4 on 2025-08-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_expense_category_alter_subscription_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
