# Generated by Django 5.2.4 on 2025-08-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='period',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
    ]
